// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice = CategorysSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Texto principal field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o texto principal do site
   * - **API ID Path**: home.main_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  main_text: prismic.KeyTextField;

  /**
   * Imagem 1 field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.img_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img_1: prismic.ImageField<never>;

  /**
   * Imagem 2 field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.img_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img_2: prismic.ImageField<never>;

  /**
   * Imagem 3 field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.img_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img_3: prismic.ImageField<never>;

  /**
   * Imagem 4 field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.img_4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img_4: prismic.ImageField<never>;

  /**
   * Imagem 5 field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.img_5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img_5: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Item in *Categorys → category → Primary → Categoria*
 */
export interface CategorysSliceDefaultPrimaryCategoryItem {
  /**
   * Categoria field in *Categorys → category → Primary → Categoria*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite a categoria
   * - **API ID Path**: categorys.default.primary.category[].category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Imagem da Categoria field in *Categorys → category → Primary → Categoria*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categorys.default.primary.category[].category_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  category_icon: prismic.ImageField<never>;
}

/**
 * Primary content in *Categorys → category → Primary*
 */
export interface CategorysSliceDefaultPrimary {
  /**
   * Categoria field in *Categorys → category → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: categorys.default.primary.category[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  category: prismic.GroupField<
    Simplify<CategorysSliceDefaultPrimaryCategoryItem>
  >;
}

/**
 * category variation for Categorys Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CategorysSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CategorysSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Categorys*
 */
type CategorysSliceVariation = CategorysSliceDefault;

/**
 * Categorys Shared Slice
 *
 * - **API ID**: `categorys`
 * - **Description**: Categorys
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CategorysSlice = prismic.SharedSlice<
  "categorys",
  CategorysSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      CategorysSlice,
      CategorysSliceDefaultPrimaryCategoryItem,
      CategorysSliceDefaultPrimary,
      CategorysSliceVariation,
      CategorysSliceDefault,
    };
  }
}
