import type { Metadata } from "next";
import type { AppProps } from 'next/app';

// Importando as fontes

// Importando Layout padrão
import Layout from "./layout";

// Importando estilos css que se aplicam a todo o site
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function App({ Component, pageProps }: AppProps) {
  return (
    <Layout className={`layout antialiased`}>
      <Component {...pageProps} />
    </Layout>
  )
}
