import type { Metadata } from "next";
import type { AppProps } from 'next/app';
import { UserProvider } from "@/context/userContext";

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// Importando estilos css que se aplicam a todo o site
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function App({ Component, pageProps }: AppProps) {
  return (
    <UserProvider>
      <Component {...pageProps} />
      <ToastContainer
        hideProgressBar={true}
        toastClassName={() => "toast_container"}
        className="toast"
      />
    </UserProvider>
  )
}
